# Generated by Django 4.1.7 on 2023-03-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradelevel_name', models.CharField(max_length=250, unique=True)),
                ('fee', models.CharField(max_length=250)),
                ('subjects', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionname', models.CharField(max_length=250)),
                ('total_students_section', models.IntegerField()),
                ('gradelevel_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.gradelevel')),
            ],
        ),
        migrations.CreateModel(
            name='GradeLevelTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradelevel_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.gradelevel')),
                ('techer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teachersnew')),
            ],
        ),
        migrations.AddField(
            model_name='studentsnew',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.section'),
        ),
    ]
