# Generated by Django 4.1.7 on 2023-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_gradelevel_section_gradelevelteacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sectionname',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
