# Generated by Django 4.1.7 on 2023-03-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_section_sectionname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradelevelteacher',
            old_name='techer_id',
            new_name='teacher_id',
        ),
    ]
