# Generated by Django 4.1.7 on 2023-03-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_techer_id_gradelevelteacher_teacher_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsnew",
            name="is_deleted",
            field=models.IntegerField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
